Repository tinymovr/Tinymovr, pull requests merged in 2022-08, with the labels that each got.

#196 Add Hall effect sensor documentation
  .vscode/tasks.json
  docs/encoders/encoders.rst
  docs/encoders/hall_pinout.jpg
  docs/index.rst
  docs/interfaces/interfaces.rst
Labels: documentation, enhancement

#197 add shortcuts documentation
  docs/api/guide.rst
Labels: documentation, enhancement

#198 CAN Timeout Watchdog (with WWDT)
  .vscode/launch.json
  docs/api/guide.rst
  firmware/src/can/can.c
  firmware/src/can/can_endpoints.c
  firmware/src/can/can_endpoints.h
  firmware/src/common.h
  firmware/src/config.h
  firmware/src/controller/controller.c
  firmware/src/main.c
  firmware/src/scheduler/scheduler.c
  firmware/src/system/system.h
  firmware/src/watchdog/watchdog.c
  firmware/src/watchdog/watchdog.h
  studio/Python/setup.py
  studio/Python/tests/test_watchdog.py
  studio/Python/tinymovr/iface/can_bus/endpoints.py
  studio/Python/tinymovr/tinymovr.py
Labels: enhancement, studio, firmware

#200 update readme
  README.md
Labels: documentation
